webservice:
  build: ./webservice/
  command: --config /go/src/app/config.json
  ports:
    - "3000:3000"
  link:
    - database
  environment:
    - DATABASE_HOST=database
database:
  build: ./database/
