webservice:
  build: ./webservice/
  command: --config /go/src/app/config.json
  ports:
    - "80:3000"
  links:
    - database
  environment:
    - DATABASE_HOST=database
database:
  build: ./database/
